[package]
name = "wordbreaker"
version = "0.1.0"
edition = "2021"
description = """
A no_std with alloc crate that rapidly finds all concatenations of words in a dictionary
that produce a certain input string.
"""
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/wordbreaker"
homepage = "https://crates.io/crates/wordbreaker"
repository = "https://github.com/ChaiTRex/wordbreaker"
authors = ["Chai T. Rex <ChaiTRex@users.noreply.github.com>"]
keywords = ["concatenation", "strings", "text"]
categories = ["no-std", "test-processing"]

[dependencies]
fst = "0.4"
unicode-normalization = "0.1.20"
unicode-segmentation = "1.9.0"