[package]
name = "wordbreaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fst = "0.4"
unicode-normalization = "0.1.20"
unicode-segmentation = "1.9.0"